proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: SingleApp
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8000
  # Follows this example:
  # https://github.com/openanalytics/shinyproxy-config-examples/tree/master/13-openid-auth0
  authentication: openid
  openid:
    auth-url: https://dev-86k35fwjrx0y5mgr.eu.auth0.com/authorize
    token-url: https://dev-86k35fwjrx0y5mgr.eu.auth0.com/oauth/token
    jwks-url: https://dev-86k35fwjrx0y5mgr.eu.auth0.com/.well-known/jwks.json
    client-id: m3pJeGpCA27tZx2pBnLPZRzn3Tgl4IaT
    # client-secret: SPECIFY USING PROXY_OPENID_CLIENT_SECRET ENV VAR!
    username-attribute: "https://shinyproxy.io/nickname"
    roles-claim: "https://shinyproxy.io/shinyproxy_roles"
    logout-url: https://dev-86k35fwjrx0y5mgr.eu.auth0.com/oidc/logout?id_token_hint=#{oidcUser.idToken.tokenValue}&post_logout_redirect_uri=https%3A%2F%2Flivebook.munksgaard.me

  admin-groups: admin

  container-log-path: ./container-logs

  docker:
    port-range-start: 20000
    image-pull-policy: Always
  specs:
    - id: 01_livebook
      display-name: Livebook
      description: Livebook instance for the Learn Programming with Elixir workshop.
      container-image: ghcr.io/cphex/learn_programming_with_elixir:main
      container-env:
        LIVEBOOK_TOKEN_ENABLED: false
        LIVEBOOK_BASE_URL_PATH: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH')}" # "/app/01_livebook"
        LIVEBOOK_WITHIN_IFRAME: true
      port: 8080
      additional-port-mappings:
        - name: livebook_extra
          port: 8081

server:
  forward-headers-strategy: native
  secure-cookies: true
  same-site-cookie: Lax
logging:
  file:
    name: shinyproxy.log
